name: PreciousStones
main: net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones
version: 2.6.2
commands:
  ps:
    description: All of the PreciousStones commands
    usage: /ps help - Displays PreciousStones commands
