bypass-blocks: []
unbreakable-blocks: []
unprotectable-blocks: []
repairable-items: [256,257,258,259,267,268,269,270,271,272,273,274,275,276,277,278,279,283,284,285,286,290,291,292,293,294,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,359]
tool-items: [256,257,258,269,270,271,273,274,275,277,278,279,284,285,286,290,291,292,293,294]
force-field-blocks:
-   title: City Protection
    block: 133
    radius: 20
    custom-height: 15
    prevent-fire: true
    prevent-place: true
    prevent-destroy: true
    prevent-vehicle-destroy: true
    prevent-explosions: true
    prevent-unprotectable: true
    prevent-flow: true
    prevent-teleport: true
    welcome-message: true
    farewell-message: true
    can-change-owner: true
    enable-on-src: true
    mixing-group: 1
    cuboid: true
    mask-on-disabled: 80
-   title: City Plot
    block: 57
    radius: 20
    custom-height: 15
    allowed-only-inside: ["City Protection"]
    plot: true
    prevent-fire: true
    prevent-place: true
    prevent-destroy: true
    prevent-vehicle-destroy: true
    prevent-explosions: true
    prevent-unprotectable: true
    prevent-flow: true
    prevent-teleport: true
    welcome-message: true
    farewell-message: true
    can-change-owner: true
    enable-on-src: true
    mixing-group: 1
    cuboid: true
    mask-on-disabled: 80
-   title: Entry Bouncer
    block: 22
    radius: 5
    prevent-entry: true
    prevent-unprotectable: true
    prevent-flow: true
    enable-on-src: true
    can-change-owner: true
    cuboid: true
    mask-on-disabled: 80
-   title: Grief Revert
    block: 41
    radius: 20
    custom-height: 15
    allow-grief: [37, 38, 39, 40]
    grief-revert: true
    apply-to-all: true
    welcome-message: true
    farewell-message: true
    enable-on-src: true
    can-change-owner: true
    mixing-group: 1
    cuboid: true
    mask-on-disabled: 80
-   title: Peace Keeper
    block: 19
    radius: 10
    prevent-pvp: true
    no-player-place: true
    prevent-mob-damage: true
    protect-animals: true
    protect-mobs: true
    cuboid: true
    mask-on-disabled: 80
-   title: Jack-o-Death
    block: 91
    radius: 5
    damage: 4
    no-conflict: true
    sneaking-bypass: true
    no-player-place: true
    mixing-group: 2
    mask-on-disabled: 80
-   title: Creature Repeller
    block: 30
    radius: 20
    prevent-mob-spawn: true
    prevent-animal-spawn: true
    remove-mob: true
    no-conflict: true
    mixing-group: 1
    cuboid: true
    mask-on-disabled: 80
-   title: Air of Atlantis
    block: 21
    radius: 10
    custom-height: 256
    air: true
    no-conflict: true
    mixing-group: 1
    cuboid: true
    mask-on-disabled: 80
-   title: Proximity Snitch
    block: 25
    radius: 5
    snitch: true
    entry-alert: true
    no-conflict: true
    mixing-group: 2
    cuboid: true
    mask-on-disabled: 80
-   title: The Shocker
    block: 97
    radius: 0
    custom-height: 3
    lightning: true
    lightning-replace-block: 0
    sneaking-bypass: true
    breakable: true
    no-conflict: true
    mixing-group: 2
    mask-on-disabled: 80
-   title: Proximity Mine
    block: 73
    radius: 1
    custom-height: 5
    mine: 5
    mine-has-fire: true
    mine-delay-seconds: 0
    breakable: true
    sneaking-bypass: true
    mixing-group: 2
    no-conflict: true
    mask-on-disabled: 80
-   title: Launch Pad
    block: 15
    radius: 1
    launch: true
    no-conflict: true
    sneaking-bypass: true
    custom-volume: 20
    mixing-group: 2
    cuboid: true
    mask-on-disabled: 80
-   title: Sky Cannon
    block: 16
    radius: 0
    custom-height: 3
    custom-volume: 20
    sneaking-bypass: true
    cannon: true
    no-conflict: true
    mixing-group: 2
    cuboid: true
    enable-with-redstone: true
    mask-on-disabled: 80
-   title: Translocator
    block: '100:14'
    radius: 8
    custom-volume: 5000
    enable-with-redstone: true
    translocation: true
    dynmap-area: true
    dynmap-disabled: true
    translocation-blacklist:
    - 57
    - 41
    cuboid: true
    mask-on-disabled: 17
-   title: GodStone
    block: 99
    radius: 5
    heal: 4
    feed: 2
    repair: 25
    neutralize-potions: [HARM, CONFUSION, BLINDNESS, HUNGER, WEAKNESS, POISON, SLOW]
    no-conflict: true
    mixing-group: 2
    cuboid: true
    mask-on-disabled: 80
-   title: Miner's Haste
    block: 8
    radius: 10
    custom-height: 128
    cuboid: true
    dynmap-area: true
    potions:
    - FAST_DIGGING
    - SPEED
    - JUMP
    potion-intensity:
    - 5
    - 3
    - 5
    enable-with-redstone: true
    apply-to-all: true
    no-fall-damage: true
    mask-on-disabled: 17
-   title: Mild Forester
    block: '18:4'
    radius: 20
    custom-height: 15
    forester: true
    ground-block: 2
    fertile-blocks:
    - 3
    - 2
    - 13
    - 87
    - 80
    - 88
    tree-types:
    - 0
    - 0
    - 0
    - 1
    - 1
    - 4
    shrub-types:
    - 1
    - 1
    - 1
    - 2
    - 2
    - 3
    - 4
    shrub-density: 64
    tree-count: 32
    grow-time: 10
    no-owner: true
    no-conflict: false
-   title: Redwood Forester
    block: '18:5'
    radius: 20
    custom-height: 15
    forester: true
    ground-block: 2
    fertile-blocks:
    - 3
    - 2
    - 13
    - 87
    - 80
    - 88
    tree-types:
    - 2
    - 2
    - 2
    - 3
    shrub-types:
    - 1
    shrub-density: 64
    tree-count: 32
    grow-time: 10
    no-owner: true
    no-conflict: false
-   title: Jungle Forester
    block: '18:6'
    radius: 20
    custom-height: 15
    forester: true
    ground-block: 2
    fertile-blocks:
    - 3
    - 2
    - 13
    - 87
    - 80
    - 88
    tree-types:
    - 0
    - 0
    - 7
    - 7
    - 7
    - 8
    - 8
    - 8
    - 8
    shrub-types:
    - 2
    shrub-density: 30
    tree-count: 64
    grow-time: 10
    no-owner: true
    no-conflict: false
-   title: Birch Forester
    block: '18:7'
    radius: 20
    custom-height: 15
    forester: true
    ground-block: 2
    fertile-blocks:
    - 3
    - 2
    - 13
    - 87
    - 80
    - 88
    tree-types:
    - 4
    - 4
    - 8
    - 8
    - 7
    shrub-types:
    - 2
    shrub-density: 85
    tree-count: 64
    grow-time: 10
    no-owner: true
    no-conflict: false
warn:
    slow-damage: true
    pvp: true
    instant-heal: true
    launch: true
    fast-damage: true
    use: true
    air: true
    slow-feeding: true
    fire: true
    cannon: true
    destroy-area: true
    destroy: true
    slow-heal: true
    entry: true
    unprotectable: true
    mine: true
    slow-repair: true
    place: true
cleanup:
    player-inactivity-purge-days: 45
    snitch-unused-purge-days: 30
settings:
    max-size-translocation: 100000
    max-size-translocation-for-redstone: 1000
    prevent-place-everywhere: false
    prevent-destroy-everywhere: false
    sneak-to-place-normal-block: true
    sneak-to-place-field: false
    show-debug-info: false
    show-default-welcome-farewell-messages: true
    dynmap-flags-disabled-by-default: true
    welcome-farewell-disabled-by-default: true
    disable-ground-info: false
    global-field-limit: 1000000
    no-refund-for-fields: false
    off-by-default: false
    log-to-hawkeye: false
    lines-per-page: 12
    disable-bypass-alerts-for-admins: false
    disable-alerts-for-admins: true
    public-block-details: false
    blacklisted-worlds: [creative_world]
    drop-on-delete: true
    version: 0
log:
    bypass-pvp: true
    pvp: true
    bypass-destroy: true
    use: true
    fire: true
    destroy: true
    destroy-area: false
    place-area: false
    entry: true
    unprotectable: true
    bypass-place: true
    place: true
    translocation: true
    rollback: true
    bypass-delete: true
    conflict-place: true
cuboid:
    visualization-blocktype: 20
    defining-blocktype: 49
visualization:
    block-type: 20
    seconds: 30
    mark-block-type: 49
    end-on-player-move: false
    frame-block-type: 20
    blocks-to-send: 100
    ticks-between-sends: 10
    default-density: 8
    max-fields-to-visualize-at-once: 5
notify:
    destroy: true
    bypass-pvp: true
    bypass-destroy: true
    bypass-unprotectable: true
    bypass-place: true
    place: true
    rollback: true
    translocation: true
    fly-zones: true
grief-undo:
    min-interval-secs: 30
    black-list:
    - 92
saving:
    frequency-seconds: 15
    max-records-per-snitch: 50
mysql:
    username: ''
    host: localhost
    enable: false
    password: ''
    database: minecraft
    port: 3306