bypass-blocks: []
unbreakable-blocks: []
unprotectable-blocks: []
repairable-items: [256,257,258,259,267,268,269,270,271,272,273,274,275,276,277,278,279,283,284,285,286,290,291,292,293,294,298,299,300,301,302,303,304,305,306,307,308,309,310,311,312,313,314,315,316,317,359]
tool-items: [269,270,271,273,274,275,277,278,279,284,285,286,290,291,292,293,294]
force-field-blocks:
-   title: City Protection
    block: 57
    radius: 20
    custom-height: 15
    prevent-fire: true
    prevent-place: true
    prevent-destroy: true
    prevent-explosions: true
    prevent-unprotectable: true
    prevent-flow: true
    prevent-teleport: true
    welcome-message: true
    farewell-message: true
    visualize-on-rightclick: true
    mixing-group: 1
    cuboid: true
-   title: Town Protection
    block: 79
    radius: 1
    customVolume: 2000000
    prevent-fire: true
    prevent-place: true
    prevent-destroy: true
    prevent-explosions: true
    prevent-unprotectable: true
    prevent-flow: true
    prevent-teleport: true
    welcome-message: true
    farewell-message: true
    visualize-on-rightclick: true
    cuboid: true
-   title: Town SubPlot
    block: 3512
    radius: 10
    custom-height: 21
    allowed-only-inside: [Town Protection]
    prevent-fire: true
    prevent-place: true
    prevent-destroy: true
    prevent-explosions: true
    prevent-unprotectable: true
    prevent-flow: true
    prevent-teleport: true
    welcome-message: true
    farewell-message: true
    visualize-on-rightclick: true
-   title: Entry Bouncer
    block: 22
    radius: 5
    prevent-entry: true
    prevent-fire: true
    prevent-place: true
    prevent-destroy: true
    prevent-explosions: true
    prevent-unprotectable: true
    prevent-flow: true
    visualize-on-rightclick: true
    cuboid: true
-   title: Jack-o-Death
    block: 91
    radius: 5
    slow-damage: true
    no-conflict: true
    mixing-group: 2
-   title: Creature Repeller
    block: 30
    radius: 20
    prevent-mob-spawn: true
    prevent-animal-spawn: true
    no-conflict: true
    additive: true
    mixing-group: 1
    cuboid: true
-   title: Air of Atlantis
    block: 21
    radius: 10
    custom-height: 128
    give-air: true
    no-conflict: true
    additive: true
    mixing-group: 1
    cuboid: true
-   title: Proximity Snitch
    block: 25
    radius: 5
    snitch: true
    entry-alert: true
    no-conflict: true
    mixing-group: 2
    cuboid: true
-   title: The Shocker
    block: 97
    radius: 0
    custom-height: 3
    lightning: true
    lightning-replace-block: 0
    breakable: true
    no-conflict: true
    mixing-group: 2
    cuboid: true
-   title: Proximity Mine
    block: 73
    radius: 1
    custom-height: 5
    mine: true
    mine-replace-block: 1
    breakable: true
    mixing-group: 2
    no-conflict: true
-   title: Launch Pad
    block: 15
    radius: 1
    launch: true
    no-conflict: true
    custom-volume: 20
    mixing-group: 2
    cuboid: true
-   title: Sky Cannon
    block: 16
    radius: 0
    custom-height: 3
    custom-volume: 20
    cannon: true
    no-conflict: true
    mixing-group: 2
    cuboid: true
-   title: Grief Revert
    block: 41
    radius: 20
    custom-height: 15
    grief-revert: true
    welcome-message: true
    farewell-message: true
    visualize-on-rightclick: true
    mixing-group: 1
    cuboid: true
-   title: GodStone
    block: 99
    radius: 5
    slow-heal: true
    slow-feed: true
    slow-repaid: true
    no-conflict: true
    mixing-group: 2
    cuboid: true
-   title: forester
    block: 86
    radius: 20
    custom-height: 15
    forester: true
    forester-shrubs: true
    no-owner: true
    no-conflict: true
-   title: Peace Keeper
    block: 19
    radius: 10
    prevent-pvp: true
    prevent-mob-damage: true
    additive: true
    cuboid: true
warn:
    slow-damage: true
    pvp: true
    instant-heal: true
    launch: true
    fast-damage: true
    use: true
    give-air: true
    slow-feeding: true
    fire: true
    cannon: true
    destroy-area: true
    destroy: true
    slow-heal: true
    entry: true
    unprotectable: true
    mine: true
    slow-repair: true
    place: true
cleanup:
    player-inactivity-purge-days: 45
    snitch-unused-purge-days: 30
settings:
    off-by-default: false
    sneaking-bypasses-damage: true
    log-to-hawkeye: false
    lines-per-page: 12
    disable-bypass-alerts-for-admins: false
    disable-alerts-for-admins: true
    public-block-details: false
    blacklisted-worlds: [creative_world]
    debug-on: false
    drop-on-delete: true
    allowed-can-break-pstones: false
forester:
    trees: 60
    interval-seconds: 1
    fertile-blocks:
    - 2
    - 3
    - 13
    - 87
log:
    bypass-pvp: true
    pvp: true
    bypass-destroy: true
    use: true
    fire: true
    destroy: true
    destroy-area: false
    place-area: false
    entry: true
    unprotectable: true
    bypass-place: true
    place: true
    rollback: true
    bypass-delete: true
    conflict-place: true
cuboid:
    visualization-blocktype: 20
    defining-blocktype: 49
visualization:
    block-type: 20
    seconds: 10
    mark-block-type: 49
    end-on-player-move: false
    frame-block-type: 20
    blocks-to-send: 100
    ticks-between-sends: 10
    default-density: 8
    max-fields-to-visualize-at-once: 5
notify:
    destroy: true
    bypass-pvp: true
    bypass-destroy: true
    bypass-unprotectable: true
    bypass-place: true
    place: true
    rollback: true
grief-undo:
    min-interval-secs: 30
    black-list:
    - 92
saving:
    frequency-seconds: 15
    max-records-per-snitch: 50
mysql:
    username: ''
    host: localhost
    enable: false
    password: ''
    database: minecraft
    port: 3306