name: PreciousStones
main: net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones
version: 5.4
softdepend: [Permissions, Help, SimpleTeams]
commands:
  ps:
    description: All of the PreciousStones commands
    usage: Syntax error
