name: PreciousStones
main: net.sacredlabyrinth.Phaed.PreciousStones.PreciousStones
version: 4.1.3
database: true
commands:
  ps:
    description: All of the PreciousStones commands
    usage: /ps help - Displays PreciousStones commands
